engine/quizzy/config/routes.rb
Rails.application.routes.draw do

    resources :image_uploads
    resources :questions
    resources :type_of_quizzes
    resources :quizzes
    get 'activate_quiz', to: 'quizzes#activate_quiz'
    get 'home', to: 'static_pages#home'
    get 'teacher', to: 'static_pages#show'
    root 'static_pages#home'
  
    get 'check_user_block', to: 'quizzes#check_user_block'
    get 'block_unblock_user', to: 'quizzes#block_unblock_user'
    
    get 'create_question',to: 'questions#create_question'
    post 'update_question', to:"questions#update_question"
    get 'students',to: 'students#index'
    get 'test_result' ,to: 'students#test_result'
    post '/type_of_quizzes/:id/upload',to: 'type_of_quizzes#upload'
    get 'show_quiz',to: 'students#show_quiz'
    post '/student/result',to: 'students#result'
    get 'show_student_list', to: 'quizzes#show_student_list'
  
    get '/quiz/result',to: 'quiz_result#index'
    get '/quiz/:id/result',to: 'quiz_result#index'
    get '/notification/:id/result',to: 'quiz_result#show_result'
    get 'upload_detail', to: 'static_pages#upload_detail'
    
    # result_notification
  
  
    
  
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  

engine/quizzy/app/views/layouts/application-engine.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <%= favicon_link_tag 'logo.png'%>
    <title>QuizMaker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>



  <body class="h-full">

  <% if user_signed_in? %>



          <div class="min-h-full">
      <!-- Off-canvas menu for mobile, show/hide based on off-canvas menu state. -->
      <div class="background-side-nav fixed inset-0 flex z-40 lg:hidden" role="dialog" aria-modal="true">
        <!--
          Off-canvas menu overlay, show/hide based on off-canvas menu state.

          Entering: "transition-opacity ease-linear duration-300"
            From: "opacity-0"
            To: "opacity-100"
          Leaving: "transition-opacity ease-linear duration-300"
            From: "opacity-100"
            To: "opacity-0"
        -->
        <div class="background-side-nav fixed inset-0 bg-gray-600 bg-opacity-75" aria-hidden="true"></div>

        <!--
          Off-canvas menu, show/hide based on off-canvas menu state.

          Entering: "transition ease-in-out duration-300 transform"
            From: "-translate-x-full"
            To: "translate-x-0"
          Leaving: "transition ease-in-out duration-300 transform"
            From: "translate-x-0"
            To: "-translate-x-full"
        -->
        <div class="side-nav relative flex-1 flex flex-col max-w-xs w-full pt-5 pb-4 bg-cyan-700">
          <!--
            Close button, show/hide based on off-canvas menu state.

            Entering: "ease-in-out duration-300"
              From: "opacity-0"
              To: "opacity-100"
            Leaving: "ease-in-out duration-300"
              From: "opacity-100"
              To: "opacity-0"
          -->
          <div class="absolute top-0 right-0 -mr-12 pt-2">
            <button type="button" class="side-nav-button ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white">
              <span class="sr-only">Close sidebar</span>
              <!-- Heroicon name: outline/x -->
              <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>

          <div class="flex-shrink-0 flex items-center px-4">
            <%= image_tag "logo.png",class: "mx-auto",style:"height:100px"  %>
          </div>
          <nav class="mt-5 flex-shrink-0 h-full divide-y divide-cyan-800 overflow-y-auto" aria-label="Sidebar">
            <div class="px-2 space-y-1">
              <!-- Current: "bg-cyan-800 text-white", Default: "text-cyan-100 hover:text-white hover:bg-cyan-600" -->
              <%= link_to root_url, class:"bg-cyan-800 text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md" do %>
                <i class="fa fa-home" style="font-size:22px"></i>&ensp;&ensp;
                Home
              <% end %>
              <%= link_to quizzes_path, class:"bg-cyan-800 text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md" do %>
                <i class="fa fa-question-circle" style="font-size:22px"></i>&ensp;&ensp;
                Quizzes
              <% end %>

              <%= link_to quiz_result_path, class:"bg-cyan-800 text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md" do %>
                <i class="fa fa-question-circle" style="font-size:22px"></i>&ensp;&ensp;
                Quiz Result Notification
              <% end %>
              <%= link_to show_student_list_path, class:"bg-cyan-800 text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md" do %>
                <i class="fa fa-user" style="font-size:22px"></i>&ensp;&ensp;
                User List
              <% end %>
            </div>
            <div class="mt-6 pt-6">
              <div class="px-2 space-y-1">

              </div>
            </div>
          </nav>
        </div>

        <div class="flex-shrink-0 w-14" aria-hidden="true">
          <!-- Dummy element to force sidebar to shrink to fit close icon -->
        </div>
      </div>

      <!-- Static sidebar for desktop -->
      <div class="hidden z-50 lg:flex lg:w-64 lg:flex-col lg:fixed lg:inset-y-0">
        <!-- Sidebar component, swap this element with another sidebar if you like -->
        <div class="flex flex-col flex-grow bg-cyan-700 pt-5 pb-4 overflow-y-auto">
          <div class="flex items-center flex-shrink-0 px-4">
            <%= image_tag "logo.png",class:"mx-auto",style:"height:100px" %>
          </div>
          <nav class="mt-5 flex-1 flex flex-col divide-y divide-cyan-800 overflow-y-auto" aria-label="Sidebar">
            <div class="px-2 space-y-1">
              <!-- Current: "bg-cyan-800 text-white", Default: "text-cyan-100 hover:text-white hover:bg-cyan-600" -->
              <%= link_to root_url, class:"bg-cyan-800 text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md" do %>
                <!-- Heroicon name: outline/home -->
                <i class="fa fa-home" style="font-size:22px"></i>&ensp;&ensp;
                Home
              <% end %>
              <%= link_to quizzes_path, class:"bg-cyan-800 text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md" do %>
                <i class="fa fa-question-circle" style="font-size:22px"></i>&ensp;&ensp;
                Quizzes
              <% end %>

              <%= link_to quiz_result_path, class:"bg-cyan-800 text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md" do %>
                <i class="fa fa-bell" style="font-size:22px"></i>&ensp;&ensp;
                Quiz Result Notification
              <% end %>
              <%= link_to show_student_list_path, class:"bg-cyan-800 text-white group flex items-center px-2 py-2 text-sm leading-6 font-medium rounded-md" do %>
                <i class="fa fa-user" style="font-size:22px"></i>&ensp;&ensp;
                User List
              <% end %>
            </div>
            <div class="mt-6 pt-6">
              <div class="px-2 space-y-1">
        
              </div>
            </div>
          </nav>
        </div>
      </div>

      <div class="lg:pl-64 flex flex-col flex-1">
        <div class="relative z-10 flex-shrink-0 flex h-16 bg-white border-b border-gray-200 lg:border-none">
          <button type="button" class="side-nav-button px-4 border-r border-gray-200 text-gray-400 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-cyan-500 lg:hidden">
            <span class="sr-only">Open sidebar</span>
            <!-- Heroicon name: outline/menu-alt-1 -->
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h8m-8 6h16" />
            </svg>
          </button>
          <!-- Search bar -->
          <div class="flex-1 px-4 flex justify-between sm:px-6  lg:mx-auto lg:px-8">
            <div class="flex-1 flex">
            </div>
            <div class="ml-4 flex items-center md:ml-6">
              <button type="button" class="hidden bg-white p-1 rounded-full text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-cyan-500">
                <span class="sr-only">View notifications</span>
                <!-- Heroicon name: outline/bell -->
                <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
                </svg>
              </button>

              <!-- Profile dropdown -->
              <div class="ml-3 relative">
                <% if user_signed_in? %>
                  
                  <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "shadow-xl bg-transparent hover:bg-red-500 text-red-700 font-semibold hover:text-white py-2 px-4 border border-red-500 hover:border-transparent hover:shadow-xl" %>
                <% else %>
                  <%= link_to "Log In",user_session_path,class: "shadow-xl bg-transparent hover:bg-green-500 text-green-700 font-semibold hover:text-white py-2 px-4 border border-green-500 hover:border-transparent hover:shadow-xl" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <main class="flex-1 pb-8">
          <!-- Page header -->
          <div class="bg-white shadow">
            <div class="px-4 sm:px-6  lg:mx-auto lg:px-8">
              <div class="py-6 md:flex md:items-center md:justify-between lg:border-t lg:border-gray-200">
                <div class="flex-1 min-w-0">
                  <!-- Profile -->
                  <div class="flex items-center">
                    <div>
                      <div class="flex items-center">
                        <img class="h-16 w-16 rounded-full sm:hidden" src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2.6&w=256&h=256&q=80" alt="">
                        <h1 class="ml-3 text-2xl font-bold leading-7 text-gray-900 sm:leading-9 sm:truncate">
                          <span class="day-message"></span>
                        </h1>
                      </div>
                      <dl class="mt-6 flex flex-col sm:ml-3 sm:mt-1 sm:flex-row sm:flex-wrap">
                        <dt class="sr-only">Company</dt>
                        <dd class="flex items-center text-sm text-gray-500 font-medium capitalize sm:mr-6">
                          <!-- Heroicon name: solid/office-building -->
                          <i class="fa fa-user mr-2"style="font-size:20px"></i>
                          <%= current_user.email %>
                        </dd>
                        <dt class="sr-only">Account status</dt>
                        <dd class="mt-3 flex items-center text-sm text-gray-500 font-medium sm:mr-6 sm:mt-0 capitalize">
                          <!-- Heroicon name: solid/check-circle -->
                          <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-cyan-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                          </svg>
                          Verified account
                        </dd>
                      </dl>
                    </div>
                  </div>
                </div>
                <div class="mt-6 flex space-x-3 md:mt-0 md:ml-4">
                  <%= link_to "Add Quiz",new_quiz_path, class: "shadow-xl float-left bg-transparent hover:bg-cyan-700 text-cyan-600 font-semibold hover:text-white py-2 px-4 border border-cyan-700 hover:border-transparent hover:shadow-xl" %>
                </div>
              </div>
            </div>
          </div>
            <%= yield %>
        </main>
      </div>
    </div>
    <% else %>
    <%= yield %>

    <% end %>
    <%= javascript_include_tag 'home'%>
  </body>
  
</html>

engine/quizzy/app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html class="h-full bg-gray-100">
  <head>
    <%= favicon_link_tag 'logo.png'%>
    <title>QuizMaker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    </head>



  <body class="h-full">
    <%= yield %>
    <%= javascript_include_tag 'home'%>
  </body>
  
</html>