engine/quizzy/config/routes.rb
Rails.application.routes.draw do

    resources :image_uploads
    resources :questions
    resources :type_of_quizzes
    resources :quizzes
    get 'activate_quiz', to: 'quizzes#activate_quiz'
    get 'home', to: 'static_pages#home'
    get 'teacher', to: 'static_pages#show'
    root 'static_pages#home'
  
    get 'check_user_block', to: 'quizzes#check_user_block'
    get 'block_unblock_user', to: 'quizzes#block_unblock_user'
    
    get 'create_question',to: 'questions#create_question'
    post 'update_question', to:"questions#update_question"
    get 'students',to: 'students#index'
    get 'test_result' ,to: 'students#test_result'
    post '/type_of_quizzes/:id/upload',to: 'type_of_quizzes#upload'
    get 'show_quiz',to: 'students#show_quiz'
    post '/student/result',to: 'students#result'
    get 'show_student_list', to: 'quizzes#show_student_list'
  
    get '/quiz/result',to: 'quiz_result#index'
    get '/quiz/:id/result',to: 'quiz_result#index'
    get '/notification/:id/result',to: 'quiz_result#show_result'
    get 'upload_detail', to: 'static_pages#upload_detail'
    
    # result_notification
  
  
    
  
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
  

engine/quizzy/app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: %i[ show edit update destroy ]
  layout "application-engine"
  # GET /quizzes or /quizzes.json
  def index
    @quizzes = Quiz.all.order('created_at')
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  end

  # POST /quizzes or /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to quizzes_path, notice: "Quiz was successfully created." }
        format.json { render :show, status: :created, location: @quiz }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  def activate_quiz
    Quiz.update_all(active: 0)
    Quiz.find(params[:quiz_id]).update(active: 1)
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to quizzes, notice: "Quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy

    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: "Quiz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show_student_list
    @students=User.where(role: "student")
    @active_quiz=Quiz.where(active: true)
    @types=TypeOfQuiz.where(quiz_id: @active_quiz.first.id)
  end

  def check_user_block
    @allow_student=AllowStudent.where(type_of_quiz_id: params[:type_of_quiz_id], user_id: params[:student_id])
    respond_to do |format|
      format.js 
    end
  end

  def block_unblock_user
    @allow_student=AllowStudent.where(type_of_quiz_id: params[:type_of_quiz_id], user_id: params[:student_id].to_i)
    if @allow_student.length == 0
      AllowStudent.create(type_of_quiz_id: params[:type_of_quiz_id], user_id: params[:student_id].to_i,block: params[:block].to_i)
    else
      @allow_student.update(block: params[:block].to_i)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quiz
      @quiz = Quiz.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def quiz_params
      params.require(:quiz).permit(:title, :description)
    end
end

engine/quizzy/app/views/quizzes/_check_user_block.html.erb
<label class="mt-4   float-left flex items-center cursor-pointer ml-8">
    <!-- toggle -->
    <div class="relative">
    <!-- input -->
    <% if @allow_student.length == 0 || @allow_student.first.block == false  %>           
        <input id="toogleA" name="activate" type="checkbox" onclick="unblockBlockUser()" class="sr-only" />
    <% else %>
        <input id="toogleA" name="activate" checked="true" onclick="unblockBlockUser()" type="checkbox" class="sr-only" />
    <% end %>          
    <!-- line -->
    <div class="w-10 h-4 bg-gray-400 rounded-full shadow-inner"></div>
    <!-- dot -->
    <div class="dot absolute w-6 h-6 bg-white rounded-full shadow -left-1 -top-1 transition"></div>
    </div>
</label>
<style>
    /* Toggle A */
    input:checked ~ .dot {
        transform: translateX(100%);
        background-color: #06b6d4;
    }
</style>
<script>
    function unblockBlockUser(){
        if($("#toogleA").is(":checked"))
        {
            block = 1
        }
        else
        {
            block = 0
        }
        $.ajax({
            type: 'get',
            data: 'type_of_quiz_id='+$("#type_of_quiz").val()+"&student_id="+$("#student_id").html()+"&block="+block,
            url: "<%= block_unblock_user_path %>"
        })
    }
</script>

engine/quizzy/app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, class: "contents") do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
        <% quiz.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

engine/quizzy/app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>">
  <!--<% if action_name != "show" %>
    <%= link_to "Show this quiz", quiz, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this quiz', edit_quiz_path(quiz), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>-->
  <tr>
    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
      <%= quiz.title %>
    </td>
    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
      <%= quiz.description %>
    </td>
    <td>     
      <label class="flex items-center cursor-pointer ml-8" onclick="activate_quiz(<%= quiz.id %>)">
        <!-- toggle -->
        <div class="relative">
          <!-- input -->
          <% if quiz.active == true %>            
            <input id="toogleA" name="activate" checked="true" type="radio" class="sr-only" />
          <% else %>
            <input id="toogleA" name="activate" type="radio" class="sr-only" />
          <% end %>          
          <!-- line -->
          <div class="w-10 h-4 bg-gray-400 rounded-full shadow-inner"></div>
          <!-- dot -->
          <div class="dot absolute w-6 h-6 bg-white rounded-full shadow -left-1 -top-1 transition"></div>
        </div>
      </label>
    </td>
    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
      <%= link_to "Edit",edit_quiz_path(quiz),class:"inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"%>
      <%= link_to "Details",type_of_quizzes_path(quiz_id: quiz.id),class:"inline-flex items-center px-4 py-2 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"%>
    </td>
  </tr>
</div>
<style>
  /* Toggle A */
  input[type="radio"]:checked ~ .dot {
    transform: translateX(100%);
    background-color: #06b6d4;
  }
</style>
<script>
  function activate_quiz(quiz_id){
    $.ajax({
      type: "get",
      data: "quiz_id="+quiz_id,
      url: "<%= activate_quiz_path %>"
    })    
  }
</script>

engine/quizzy/app/views/quizzes/check_user_block.js.erb
$('#check_user').html("<%= j (render partial: 'quizzes/check_user_block') %>")

engine/quizzy/app/views/quizzes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl uppercase">Editing quiz</h1>

  <%= render "form", quiz: @quiz %>
  <%= link_to "Back to quizzes", quizzes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

engine/quizzy/app/views/quizzes/index.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
<% end %>
<!-- This example requires Tailwind CSS v2.0+ -->
<div class="w-full block">
<div class="flex flex-col">
  <h2 class="max-w-6xl mb-2 mt-8 px-4 text-3xl uppercase text-left leading-6 font-medium text-gray-500 sm:px-6 lg:px-8">
    Quizzes
  </h2>
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <table class="min-w-full divide-y divide-gray-200">
          <thead class="bg-gray-50">
            <tr>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Title
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Description
              </th>
              <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Enable
              </th>
              <th scope="col" class="text-center px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Action
              </th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <%= render @quizzes %> 
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
</div>

engine/quizzy/app/views/quizzes/new.html.erb
<div class="mx-auto w-full text-gray-500 px-4 py-14 bg-white mt-4 shadow-xl">
  <h1 class="font-bold text-4xl uppercase">New quiz</h1>

  <%= render "form", quiz: @quiz %>

  <%= link_to 'Back to quizzes', quizzes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

engine/quizzy/app/views/quizzes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @quiz %>

    <%= link_to 'Edit this quiz', edit_quiz_path(@quiz), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this quiz', quiz_path(@quiz), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to quizzes', quizzes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

engine/quizzy/app/views/quizzes/show_student_list.html.erb
<div class="w-full block">
<div class="flex flex-col">
  <h2 class="max-w-6xl mb-2 mt-8 px-4 text-3xl uppercase text-left leading-6 font-medium text-gray-500 sm:px-6 lg:px-8">
    Student List
  </h2>
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Id
                    </th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Email
                    </th>
                    <th scope="col" class="text-left px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                        Action
                    </th>
                    </tr>
                </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <% @students.each do |student| %>
                <td id="student_id" class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    <%= student.id %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    <%= student.email %>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                    <select name="type_name" class="float-left" id="type_of_quiz" onchange="checkUserBlock(<%= student.id %>)">
                        <option value="">Select test</option>
                        <% @types.each do |type| %>
                            <option value=<%= type.id %>><%= type.type.name%></option>
                        <% end %>
                    </select>
                    <div id="check_user">
                    </div>
                </td>
            <% end %> 
          </tbody>
        </div>
    </div>
</div>
      
<script>
    function checkUserBlock(student_id){
        $.ajax({
            type: 'get',
            data: 'type_of_quiz_id='+$("#type_of_quiz").val()+"&student_id="+student_id,
            url: "<%= check_user_block_path %>"
        })
    }
</script>